### ISSUE TITLE
FE: move out repeating 'isMounted' logic to the hook

### ISSUE THREAD

**Issue by ArtsiomLysianok** [Rails-course/trucking#56]
I see that you need to track the mounted state in a number of different components, and you have written a lot of boilerplate code
https://github.com/Rails-course/trucking/blob/f7c089acb82f138efdb0670ba336549aeb5030bc/app/javascript/components/Users/form/CreateForm.tsx#L24
https://github.com/Rails-course/trucking/blob/f7c089acb82f138efdb0670ba336549aeb5030bc/app/javascript/components/Users/form/CreateForm.tsx#L47
https://github.com/Rails-course/trucking/blob/f7c089acb82f138efdb0670ba336549aeb5030bc/app/javascript/components/Users/form/CreateForm.tsx#L54
I propose to move it out to the custom hook.

**Comment by NDragneelL9** [comment]
We found a way to send data to front-end through components props. So instead of using useEffect and mounting states we will just refactor out code with using component props

**Comment by NDragneelL9** [comment]
Example of using props to send data: https://github.com/Rails-course/trucking/commit/f52a9af3409e3e34fd4ef3f8a064f159041f0a07

**Comment by ArtsiomLysianok** [comment]
@NDragneelL9 Go for it and close the issue when refactoring is done.
